language: node_js
node_js:
  - "node"
script: npm run build
cache:
  directories:
    - node_modules
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  fqdn: "staging.denverdevs.org"
  on:
    branch: master